[general]
import = ["~/.config/alacritty/themes/aura.toml"]

[window]
startup_mode = "Maximized"

[font]
normal = { family = "FiraCode NerdFont Ret", style = "Retina" }
size = 12

[selection]
save_to_clipboard	= true

[scrolling]
multiplier = 5

[cursor]
style = { shape = "Underline", blinking = "Always" }
thickness = 0.5
blink_interval = 300

[mouse]
hide_when_typing = true
